//! Generates `webview/src/generated/wire.ts` from the Rust wire payload
//! structs (G11). The file is checked in. CI re-runs this test and
//! `git diff --exit-code`s; drift between the Rust definitions and
//! the TypeScript declarations becomes a CI failure.
//!
//! Run locally: `cargo test -p foldit-gui --test export_wire_types`.
//! The test always succeeds (it's an export, not an assertion); the
//! drift check is the subsequent git-diff in CI.

use specta::Types;
use specta_typescript::Typescript;

/// Wire-contract version. Bumped by hand whenever the shape of any wire
/// payload struct changes, so a plugin built against an older contract can
/// detect the mismatch at mount time. Exported into `wire.ts` below.
const BRIDGE_CONTRACT_VERSION: u32 = 1;

use foldit_gui::{
    ActionInfo, ActionsSection, AppCommand, AppPhase, CheckpointInfo, CheckpointKindTag,
    EntitySelection, FilterStatus, HistoryCommand, HistoryLiveUpdate, HistorySection, OpDispatch,
    PanelInfo, PanelPosition, PanelsSection, ParamConstraint, ParamSpec, ParamType, ParamValue,
    PluginGroupInfo, ProgressEntry, ProgressSection, SceneEntityInfo, SegmentInfo, SelectionSection,
    SettingsTabInfo, ViewSection, ViewportInput,
};

#[test]
#[allow(
    clippy::expect_used,
    reason = "a failed type export should fail this test loudly, which is the intended behavior"
)]
fn export_wire_types_to_ts() {
    let types = Types::default()
        .register::<HistorySection>()
        .register::<HistoryLiveUpdate>()
        .register::<CheckpointInfo>()
        .register::<CheckpointKindTag>()
        .register::<FilterStatus>()
        .register::<HistoryCommand>()
        .register::<ActionInfo>()
        .register::<ParamSpec>()
        .register::<ParamType>()
        .register::<ParamValue>()
        .register::<ParamConstraint>()
        .register::<SegmentInfo>()
        .register::<SelectionSection>()
        .register::<EntitySelection>()
        .register::<PanelsSection>()
        .register::<PanelPosition>()
        .register::<ProgressSection>()
        .register::<ProgressEntry>()
        .register::<AppPhase>()
        .register::<AppCommand>()
        .register::<OpDispatch>()
        .register::<ViewportInput>()
        .register::<ViewSection>()
        .register::<SceneEntityInfo>()
        .register::<PluginGroupInfo>()
        .register::<PanelInfo>()
        .register::<SettingsTabInfo>()
        .register::<ActionsSection>();

    // The TS app lives at the workspace root (`webview/`), outside this
    // crate, so resolve the root by walking up to the manifest that owns
    // the `[workspace]` table rather than joining off CARGO_MANIFEST_DIR.
    let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .find(|dir| {
            std::fs::read_to_string(dir.join("Cargo.toml"))
                .is_ok_and(|toml| toml.contains("[workspace]"))
        })
        .expect("workspace root (Cargo.toml with [workspace]) not found above the crate");
    let path = workspace_root.join("webview/src/generated/wire.ts");

    let header = format!(
        "// AUTO-GENERATED by `cargo test -p foldit-gui --test export_wire_types`.\n\
         // Do not edit by hand. CI runs the test and `git diff --exit-code`s\n\
         // this file; drift = CI failure.\n\
         \n\
         export const BRIDGE_CONTRACT_VERSION = {BRIDGE_CONTRACT_VERSION};\n",
    );

    Typescript::default()
        .header(header)
        .export_to(&path, &types, specta_serde::Format)
        .expect("export wire types");
}
