//! GUI ↔ runner parameter wire layer.
//!
//! `foldit-gui` deliberately does not depend on `foldit-runner`, so the
//! orchestrator-native `Param*` types and their gui-wire twins live in
//! separate crates with no shared trait. The orphan rule forbids a
//! `From` impl here (both types are foreign to this crate), so the
//! conversions are free functions generated by the `mirror_enum!`
//! macro below.
//!
//! Also hosts [`build_actions_list`], which projects the orchestrator's
//! ops catalog into the GUI's `ActionInfo` shape.

use foldit_gui::state::{
    ParamConstraint as WireParamConstraint, ParamType as WireParamType,
    ParamValue as WireParamValue,
};
use foldit_runner::Orchestrator;
use foldit_runner::orchestrator::{
    ParamConstraint as RunnerParamConstraint,
    ParamSpec as RunnerParamSpec, ParamType as RunnerParamType, ParamValue,
};

/// Build the GUI's actions list by joining each plugin's manifest
/// `[[buttons]]` array with its bridge-side op registration. The
/// orchestrator's `ops_catalog()` already does the join; this wrapper
/// just maps each `CatalogEntry` to the GUI's `ActionInfo` shape and
/// gates `enabled` on the current orchestrator lock state.
///
/// `enabled` policy: any active lock disables every catalog entry --
/// the wave-1 round-trip only runs one op at a time. Per-op
/// compatibility (wiggle while predict is running, etc.) lights up
/// when `LockTargets`-style focus reasoning lands per-button, on top
/// of the catalog.
///
/// `active` policy: not yet wired (the bridge doesn't expose
/// op-instance metadata back through the orchestrator). Always false
/// for now; the GUI renders no "currently running" state.
pub fn build_actions_list(
    orchestrator: &Option<Orchestrator>,
) -> Vec<foldit_gui::state::ActionInfo> {
    use foldit_gui::state::ActionInfo;

    let Some(orch) = orchestrator else {
        return vec![];
    };

    let any_lock_held = !orch.locked_entities().is_empty();

    orch.ops_catalog()
        .into_iter()
        .map(|entry| ActionInfo {
            op_id: entry.op_id,
            plugin_id: entry.plugin_id,
            display: entry.display,
            icon_path: entry.icon_path.to_string_lossy().into_owned(),
            enabled: !any_lock_held,
            active: false,
            hotkey: entry.hotkey,
            tooltip: entry.tooltip,
            params: entry
                .params
                .into_iter()
                .map(param_spec_to_wire)
                .collect(),
        })
        .collect()
}

/// Generate a structural conversion `fn` between two enums that mirror
/// each other variant-for-variant. Each variant is named once with its
/// field shape; the same `(bindings)` / `{ bindings }` token tree both
/// destructures the source and reconstructs the destination. Adding a
/// `Param*` variant becomes a one-line edit per direction instead of
/// an easy-to-desync match arm. Mirrors the spirit of viso's
/// `shader_registry!`.
macro_rules! mirror_enum {
    // Entry: function signature + braced variant list. Hands off to the
    // `@build` muncher with an empty match-arm accumulator.
    (
        $(#[$meta:meta])*
        $vis:vis fn $name:ident($arg:ident: $From:ident) -> $To:ident
        { $($variants:tt)+ }
    ) => {
        $(#[$meta])*
        $vis fn $name($arg: $From) -> $To {
            mirror_enum!(@build $From, $To, $arg, { } $($variants)+)
        }
    };

    // No variants left: emit the accumulated match. (A bare `:tt`-optional
    // shape would be ambiguous with the `,` separator, so we munch instead,
    // dispatching on the delimiter that follows each variant ident.)
    (@build $From:ident, $To:ident, $arg:ident, { $($arms:tt)* }) => {
        match $arg { $($arms)* }
    };
    // `Variant { fields.. }` — struct-shaped.
    (@build $From:ident, $To:ident, $arg:ident, { $($arms:tt)* }
        $variant:ident { $($field:ident),+ $(,)? } $(, $($rest:tt)+)?) => {
        mirror_enum!(@build $From, $To, $arg,
            { $($arms)* $From::$variant { $($field),+ } => $To::$variant { $($field),+ }, }
            $($($rest)+)?)
    };
    // `Variant(bindings..)` — tuple-shaped.
    (@build $From:ident, $To:ident, $arg:ident, { $($arms:tt)* }
        $variant:ident ( $($bind:ident),+ $(,)? ) $(, $($rest:tt)+)?) => {
        mirror_enum!(@build $From, $To, $arg,
            { $($arms)* $From::$variant ( $($bind),+ ) => $To::$variant ( $($bind),+ ), }
            $($($rest)+)?)
    };
    // `Variant` — unit.
    (@build $From:ident, $To:ident, $arg:ident, { $($arms:tt)* }
        $variant:ident $(, $($rest:tt)+)?) => {
        mirror_enum!(@build $From, $To, $arg,
            { $($arms)* $From::$variant => $To::$variant, }
            $($($rest)+)?)
    };
}

fn param_spec_to_wire(
    spec: RunnerParamSpec,
) -> foldit_gui::state::ParamSpec {
    foldit_gui::state::ParamSpec {
        name: spec.name,
        display_name: spec.display_name,
        description: spec.description,
        param_type: param_type_to_wire(spec.param_type),
        default: spec.default.map(param_value_to_wire),
        constraints: spec.constraints.map(param_constraint_to_wire),
    }
}

mirror_enum! {
    fn param_type_to_wire(t: RunnerParamType) -> WireParamType {
        Int, Float, Bool, String, Enum, Vec3
    }
}

mirror_enum! {
    fn param_value_to_wire(v: ParamValue) -> WireParamValue {
        Int(x), Float(x), Bool(x), String(x), Vec3(x)
    }
}

mirror_enum! {
    /// Convert a wire-side `ParamValue` (deserialized from an `OpDispatch`
    /// envelope) into the orchestrator-native form the dispatch calls
    /// expect. Inverse of [`param_value_to_wire`].
    pub(crate) fn param_value_from_wire(v: WireParamValue) -> ParamValue {
        Int(x), Float(x), Bool(x), String(x), Vec3(x)
    }
}

mirror_enum! {
    fn param_constraint_to_wire(c: RunnerParamConstraint) -> WireParamConstraint {
        IntRange { min, max }, FloatRange { min, max },
        EnumValues(x), StringPattern(x)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `param_value_from_wire` must be the exact inverse of
    /// `param_value_to_wire` across every variant, so values the GUI
    /// posts back through `OpDispatch.params` reach plugins unchanged.
    #[test]
    fn param_value_wire_roundtrip() {
        let cases = [
            ParamValue::Int(7),
            ParamValue::Float(0.25),
            ParamValue::Bool(true),
            ParamValue::String("alpha".to_string()),
            ParamValue::Vec3([1.0, -2.0, 3.5]),
        ];
        for native in cases {
            let back = param_value_from_wire(param_value_to_wire(native.clone()));
            assert_eq!(back, native);
        }
    }
}
