/**
 * SettingsPanel - Schema-driven settings UI
 *
 * A full Panel that renders form controls from a JSON Schema (generated by
 * schemars on the Rust side). Top-level object properties with titles become
 * sections selected via a category dropdown. Within each section:
 *   - boolean  → Checkbox
 *   - number with min/max → Slider
 *   - enum (string variants) → SelectDropdown
 *   - object with properties → labeled subsection (recurses, any depth)
 *
 * Nullable variants render the same control as their non-nullable form:
 * type arrays like ["boolean", "null"] and anyOf: [schema, {"type": "null"}]
 * wrappers are unwrapped before the control is chosen (see settingsSchema.ts),
 * and a null or absent value falls back to the control's concrete default;
 * there is no indeterminate state.
 *
 * Maintains optimistic local state so controls respond instantly. The local
 * state syncs from the backend whenever new values arrive via props.
 *
 * Adding a new annotated field to the Rust struct automatically produces
 * a new control here; no GUI changes required.
 */

import { Component, For, JSX, Show, createEffect, createMemo, createSignal } from 'solid-js';

import Checkbox from './Checkbox';
import SelectDropdown from './SelectDropdown';
import Slider from './Slider';
import { controlKind, extractEnumValues, isGroupOfGroups, resolveFieldSchema } from './settingsSchema';

// Props

export interface SettingsPanelProps {
	schema: any;
	values: any;
	onUpdate: (updated: any) => void;
	header?: JSX.Element;
	footer?: JSX.Element;
}

// Helpers

function getByPath(obj: any, path: string[]): any {
	let cur = obj;
	for (const key of path) {
		if (cur == null) return undefined;
		cur = cur[key];
	}
	return cur;
}

function setByPath(obj: any, path: string[], value: any): any {
	if (path.length === 0) return value;
	const clone = Array.isArray(obj) ? [...obj] : { ...obj };
	clone[path[0]] = setByPath(clone[path[0]] ?? {}, path.slice(1), value);
	return clone;
}

/** snake_case → Title Case */
function formatLabel(value: string): string {
	return value.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

// Schema-shape interpretation (nullable unwrapping, $ref resolution, enum
// extraction, control-kind decisions) lives in settingsSchema.ts so it is
// unit-testable without rendering components.

// Schema field renderer

// Exported so panels rendering a flat (sectionless) schema can reuse the
// exact control renderer without going through the section-dropdown layout.
export function SchemaField(props: {
	fieldKey: string;
	schema: any;
	rootSchema: any;
	path: string[];
	value: () => any;
	values: () => any;
	onUpdate: (path: string[], value: any) => void;
}) {
	const resolved = () => resolveFieldSchema(props.schema, props.rootSchema);
	const label = () => resolved().title ?? formatLabel(props.fieldKey);

	const kind = () => controlKind(props.schema, props.rootSchema);

	const isSlider = () => kind() === 'slider';

	const isBool = () => kind() === 'checkbox';

	const enumValues = () => extractEnumValues(resolved());

	return (
		<>
			<Show when={isSlider()}>
				{(() => {
					const s = resolved();
					const step = s.step ?? 0.01;
					const decimals = step < 0.01 ? 3 : step < 1 ? 2 : 0;
					return (
						<div class="col-span-full space-y-0.5">
							<div class="flex justify-between text-xs text-white/60">
								<span>{label()}</span>
								<span>{(props.value() ?? s.default ?? s.minimum)?.toFixed(decimals)}</span>
							</div>
							<Slider
								min={s.minimum}
								max={s.maximum}
								step={step}
								value={props.value() ?? s.default ?? s.minimum}
								onChange={(v) => props.onUpdate(props.path, v)}
							/>
						</div>
					);
				})()}
			</Show>

			<Show when={isBool()}>
				<Checkbox
					label={label()}
					checked={props.value() ?? false}
					option_name={props.path.join('.')}
					onToggle={(_name, checked) => props.onUpdate(props.path, checked)}
				/>
			</Show>

			<Show when={kind() === 'select' && enumValues()}>
				{(() => {
					const vals = enumValues()!;
					const labels = vals.map(formatLabel);
					const labelToRaw = new Map(vals.map((v, i) => [labels[i], v]));
					return (
						<SelectDropdown
							title={label()}
							options={labels}
							value={formatLabel(props.value() ?? resolved().default ?? vals[0] ?? '')}
							option_name={props.path.join('.')}
							onChange={(_, formatted) => {
								const raw = labelToRaw.get(formatted) ?? formatted;
								props.onUpdate(props.path, raw);
							}}
						/>
					);
				})()}
			</Show>

			<Show when={kind() === 'group'}>
				{/* Groups always span the full panel width so a nested group is
				    never crammed into a half-width grid cell. */}
				<div class="col-span-full pt-1">
					{/* A group whose children are all groups (e.g. a `bonds`
					    wrapper around `hydrogen_bonds` + `disulfide_bonds`) is a
					    redundant level: skip its own header and promote the child
					    groups directly so they read as clean subsections. */}
					<Show when={!isGroupOfGroups(props.schema, props.rootSchema)}>
						<div class="text-xs uppercase tracking-wide text-white/50 pb-1">{label()}</div>
					</Show>
					<SchemaFields
						schema={resolved()}
						rootSchema={props.rootSchema}
						parentPath={props.path}
						values={props.values}
						onUpdate={props.onUpdate}
					/>
				</div>
			</Show>
		</>
	);
}

// Fields list for a single section

function SchemaFields(props: {
	schema: any;
	rootSchema: any;
	parentPath: string[];
	values: () => any;
	onUpdate: (path: string[], value: any) => void;
}) {
	const fields = createMemo(() => {
		const properties = props.schema?.properties;
		if (!properties) return [];
		return Object.entries(properties).map(([key, fieldSchema], i, all) => {
			const kind = controlKind(fieldSchema as any, props.rootSchema);
			const prevKind = i > 0 ? controlKind(all[i - 1][1] as any, props.rootSchema) : kind;
			return {
				key,
				schema: fieldSchema as any,
				path: [...props.parentPath, key],
				// Break the half-width auto-flow when the control kind changes so a
				// checkbox run never shares a row with a taller select.
				breakBefore: i > 0 && kind !== prevKind,
			};
		});
	});

	return (
		// Leaf controls flow into two columns; group controls add col-span-full
		// (in SchemaField) so they break to their own full-width row.
		<div class="grid grid-cols-2 gap-2 items-start">
			<For each={fields()}>
				{(field) => (
					<>
						<Show when={field.breakBefore}>
							<div class="col-span-full h-0" />
						</Show>
						<SchemaField
							fieldKey={field.key}
							schema={field.schema}
							rootSchema={props.rootSchema}
							path={field.path}
							value={() => getByPath(props.values(), field.path)}
							values={props.values}
							onUpdate={props.onUpdate}
						/>
					</>
				)}
			</For>
		</div>
	);
}

// Main component

const SettingsPanel: Component<SettingsPanelProps> = (props) => {
	// Optimistic local state — gives instant UI feedback while IPC round-trips.
	// Syncs from backend whenever new values arrive via props.
	const [local, setLocal] = createSignal<any>(null);

	createEffect(() => {
		// Deep-read props.values to track the SolidJS store, then snapshot
		// into a plain object for local state.
		const v = props.values;
		if (v != null) {
			setLocal(JSON.parse(JSON.stringify(v)));
		}
	});

	const currentValues = () => local() ?? props.values;

	const handleFieldUpdate = (path: string[], value: any) => {
		const updated = setByPath(currentValues(), path, value);
		setLocal(updated);
		props.onUpdate(updated);
	};

	// Parse sections from schema
	const sections = createMemo(() => {
		const schema = props.schema;
		if (!schema?.properties) return [];

		return Object.entries(schema.properties)
			.filter(([_, v]: [string, any]) => {
				const s = resolveFieldSchema(v, schema);
				return s.type === 'object' || s.properties != null;
			})
			.map(([key, subSchema]: [string, any]) => {
				const s = resolveFieldSchema(subSchema, schema);
				return { key, schema: s, label: s.title ?? formatLabel(key) };
			});
	});

	// Category selector
	const [activeSection, setActiveSection] = createSignal('');
	createEffect(() => {
		const s = sections();
		if (s.length > 0 && !s.find(sec => sec.key === activeSection())) {
			setActiveSection(s[0].key);
		}
	});

	const activeSchema = () => sections().find(s => s.key === activeSection());

	return (
		<div class="text-white pt-2">
			<Show when={props.header}>
				{props.header}
			</Show>

			<Show
				when={sections().length > 0}
				fallback={<p class="text-xs text-white/40 pt-3">Loading...</p>}
			>
				<SelectDropdown
					title=""
					options={sections().map(s => s.label)}
					value={activeSchema()?.label ?? ''}
					option_name="__section"
					onChange={(_, label) => {
						const sec = sections().find(s => s.label === label);
						if (sec) setActiveSection(sec.key);
					}}
				/>

				<Show when={activeSchema()}>
					<div class="pt-2">
						<SchemaFields
							schema={activeSchema()!.schema}
							rootSchema={props.schema}
							parentPath={[activeSchema()!.key]}
							values={currentValues}
							onUpdate={handleFieldUpdate}
						/>
					</div>
				</Show>
			</Show>

			<Show when={props.footer}>
				{props.footer}
			</Show>
		</div>
	);
};

export default SettingsPanel;
