[puzzle]
title = "Sheets Together"
view_setup = "view_clashes_hbonds_hydrophobic_stubs"
scorefxn = "ref2015_cart"
start_energy = 1492.5764
completion_score = 8900.0
min_moves = 1
guide_visible = false
can_align_guide = false
use_dof_tethers = false

[puzzle.structure]
path = "structure.pdb"
format = "pdb"
ss = "EEEEEELLLLLLLLLLLLEEEEEE"
# original hash: 13945680fd79e7bca2cc69c87d1f382b

[puzzle.files]
# filters: 956d0f21f2d774ec42e7dfaf06bd472a
# puzzle_setup: 76a950724cac7f371212a3aacd430801

[puzzle.camera]
center = [11.96, 18.25, 17.78]
eye = [-2.98, -20.72, -10.19]
up = [0.95, -0.19, -0.24]

[[puzzle.filter]]
type = "HBondCount"
plugin = "rosetta"
bonus = -200
min_bonds = 12

[[sequence]]
text = "The other major type of SECONDARY STRUCTURE in proteins are BETA-SHEETS (or SHEETS for short)."
color = "science"
point_to = "sheet"

[[sequence]]
text = "The sidechains of the SHEETS alternate pointing up and down away from the plane of the sheet itself."
color = "science"
point_to = "sidechain"
point_to_index = 20

[[sequence]]
text = "Try dragging this sheet closer to the other to make more HYDROGEN BONDS! Pull the blue and red dots near each other so the flat zig zags line up!"
color = "game"
point_to = "sheet"

[[sequence]]
text = "Once you have dragged the sheets closer (but not so close that they CLASH), try pressing WIGGLE."
color = "game"
point_to = "wiggle"

[[sequence]]
text = "Hydrogen bonds form when these zig-zaggy sheets line up together like this."
color = "game"
point_to = "hbond"
