[puzzle]
title = "Intro to Foldit"
view_setup = "view_clashes_sidechain"
scorefxn = "ref2015_cart"
start_energy = 390.4476
completion_score = 7700.0
min_moves = 1
guide_visible = false
can_align_guide = false
use_dof_tethers = false

[puzzle.structure]
format = "coords"
ss = "EEE"
data = "Q09PUkRTMDAAAAAwQHiDEr+1Hrg/2p++QUdMTgAAAAFOICAgQCaXjb9LxqhAAgxKQUdMTgAAAAFDQSAgP+l41b7m6Xk/RN0vQUdMTgAAAAFDICAgQBRJuj6KPXG9yLQ5QUdMTgAAAAFPICAgQDQ5WD7wIMVAN52yQUdMTgAAAAFDQiAgP8U/fT+FP31AXeNUQUdMTgAAAAFDRyAgP0PXCj/xR65AHlYEQUdMTgAAAAFDRCAgP6ysCEAkzM0/0SbpQUdMTgAAAAFPRTEgvw8aoD/rQ5ZAJEm6QUdMTgAAAAFORTIgQJeFH797321AAFHsQUdMTgAAAAExSCAgQILZF8AVoctAAi0OQUdMTgAAAAEySCAgQISLRL/HjVA/QQYlQUdMTgAAAAEzSCAgP/41P7+/3ztAJfO2QUdMTgAAAAFIQSAgQGC0OT5R64VAap++QUdMTgAAAAExSEIgQFHKwT+aXjVADbItQUdMTgAAAAEySEIgP1O2Rj7euFJAgLQ5QUdMTgAAAAExSEcgQAP3zz/awINAhPXDQUdMTgAAAAEySEcgv4/fO0AYAAA/+DEnQUdMTgAAAAExSEUyv32yLT+iLQ5AUPXDQUdMTgAAAAEySEUyPxrhSL94Uew/LEm6QUdMWQAAAAJOICAgvd87ZL+Cbpi/GRaHQUdMWQAAAAJDQSAgv65WBL4euFK/D52yQUdMWQAAAAJDICAgwA/O2b66XjU+ibpeQUdMWQAAAAJPICAgPiPXCr+rhR8/wCDFQUdMWQAAAAJIICAgPwwIMb8otDm/seuFQUdMWQAAAAIxSEEgvso9ccADItG/TlYEQUdMWQAAAAIySEEgv7dLxz9RaHO/u0OWQVRZUgAAAANOICAgwB+uFD/oUey/t41QQVRZUgAAAANDQSAgwGGJNz/HKwLAIan8QVRZUgAAAANDICAgwEsSbz+sCDHAa+dtQVRZUgAAAANPICAgwJYtDj/HKwLAEKPXQVRZUgAAAANPWFQgv/TdL0BONT+/yuFIQVRZUgAAAANDQiAgv43ztkBrxqi+x64UQVRZUgAAAANDRyAgv56XjUBDxqg/V41QQVRZUgAAAANDRDEgvmFHrkCXztm+/nbJQVRZUgAAAANDRDIgvwIMSkBedsk/9++eQVRZUgAAAANDRTEgPwQYk0ClcKQ/F0vHQVRZUgAAAANDRTIgPr1wpECRFoc/50vHQVRZUgAAAANDWiAgP40OVkCehytAORaHQVRZUgAAAANPSCAgvzrhSD9eNT/ADAgxQVRZUgAAAANIICAgwEHKwT/ggxK++NT+QVRZUgAAAANIQSAgv6NT+EBNwo/AHiTdQVRZUgAAAAMxSEIgwDAAAEB5qfy/31wpQVRZUgAAAAMySEIgv/eNUEAOVgQ/b987QVRZUgAAAANIRDEgveFHrkCnvne/uuFIQVRZUgAAAANIRDIgvx64UkA+dslAOXjVQVRZUgAAAANIRTEgP5rAg0DAMSc++NT+QVRZUgAAAANIRTIgP9crAkC2NT9ALEm6QVRZUgAAAANISCAg"

[puzzle.files]
# puzzle_setup: f15f975020fc1e5f5a4e26da5cb519d7

[puzzle.camera]
center = [17, 4.9, -22]
eye = [-11, 4.3, 20]
up = [0.066, 1, 0.059]

[[sequence]]
text = "Welcome to educational mode! In this tutorial, we'll be going through some of the basics of protein biochemistry using Foldit."
point_to = "level"

[[sequence]]
text = "SCIENCE facts will be in GREEN."
color = "science"

[[sequence]]
text = "CLASHES are bad in proteins!"
color = "science"
point_to = "clash"

[[sequence]]
text = """
A CLASH shows where two atoms of the protein are too close together.
When atoms get too close, they push each other away! This CLASH tells us that the atoms of these two SIDECHAINS are too close together, and want to push each other away!"""
color = "science"
point_to = "clash"

[[sequence]]
text = "You can DRAG SIDECHAINS with the mouse. Sidechains can only be in certain positions. Try exploring by giving the sidechain a big pull in every direction to see what it does!"
color = "game"
point_to = "sidechain"

[[sequence]]
text = "Get rid of this CLASH to win the level!"
color = "game"
point_to = "clash"

[[on_event]]
event = "level_complete"
text = "If you want to continue exploring a level after you've beaten it, you can still change things and go onto the next level whenever you're ready."
color = "game"
point_to = "level"
