inherits = "intro"

[gui]
simplified_filter_display = true
disable_advanced_mode = true
disable_tools_tab = true
disable_action_options_tab = true

[actions]
PullSidechain = true
LocalMinimizePull = true
LockCopy = true
LockToggle = true
BandAddDrag = true
BandDelete = true
BandEnableAll = true
BandDisableAll = true
Repack = true
GlobalMinimize = true
